In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
mojo_upd_df = pd.read_csv('Mojo_budget_update.csv')

In [4]:
mojo_upd_df = mojo_upd_df.loc[pd.notnull(mojo_upd_df["release_date"])].reset_index(drop=True)

In [5]:
mojo_upd_df = mojo_upd_df.loc[pd.notnull(mojo_upd_df["mpaa"])].reset_index(drop=True)

In [6]:
mojo_upd_df = mojo_upd_df.drop(["distributor","writer","producer","composer","cinematographer","international","worldwide","genre_2","genre_3","genre_4","trivia","html"],axis=1)

In [7]:
mojo_upd_df = mojo_upd_df.loc[pd.notnull(mojo_upd_df["domestic"])].reset_index(drop=True)

In [8]:
mojo_upd_df = mojo_upd_df.loc[pd.notnull(mojo_upd_df["main_actor_4"])].reset_index(drop=True)

In [9]:
#Convert run_time in to minutes
times = []

for index,row in mojo_upd_df.iterrows():
    vals = row.run_time.split(" ")
    if len(vals)>2:
        run_time = int(vals[0])*60 + int(vals[2])    
    else:
        run_time = int(vals[0])*60
    times.append(run_time)

mojo_upd_df["runtime_conv"] = times

In [10]:
#Combining release date and year

full_date = []

for index,row in mojo_upd_df.iterrows():
    vals = str(row["release_date"]) + " " + str(row["year"])
    full_date.append(vals)

mojo_upd_df["full_date"] = full_date   
mojo_upd_df["full_date"] = pd.to_datetime(mojo_upd_df["full_date"])                    
mojo_upd_df.head()

,movie_id,title,year,mpaa,release_date,run_time,director,main_actor_1,main_actor_2,main_actor_3,main_actor_4,budget,domestic,genre_1,runtime_conv,full_date
0,tt0099165,The Bonfire of the Vanities,1990,R,December 22,2 hr 5 min,Brian De Palma,Tom Hanks,Bruce Willis,Melanie Griffith,Kim Cattrall,47000000.0,15691192.0,Comedy,125,1990-12-22
1,tt0099611,Frankenhooker,1990,R,June 1,1 hr 25 min,Frank Henenlotter,James Lorinz,Joanne Ritchie,Patty Mullen,J.J. Clark,2500000.0,205068.0,Comedy,85,1990-06-01
2,tt0099674,The Godfather: Part III,1990,R,December 25,2 hr 42 min,Francis Ford Coppola,Al Pacino,Diane Keaton,Andy Garcia,Talia Shire,54000000.0,66666062.0,Crime,162,1990-12-25
3,tt0099747,Havana,1990,R,December 14,2 hr 24 min,Sydney Pollack,Robert Redford,Lena Olin,Alan Arkin,Tomas Milian,40000000.0,9243140.0,Drama,144,1990-12-14
4,tt0100029,Lionheart,1990,R,January 11,1 hr 48 min,Sheldon Lettich,Jean-Claude Van Damme,Harrison Page,Deborah Rennard,Lisa Pelikan,6000000.0,24078196.0,Action,108,1990-01-11

In [12]:
mojo_upd_df = mojo_upd_df.drop(["run_time","release_date"],axis=1)

KeyError: "['run_time', 'release_date'] not found in axis"

In [13]:
mojo_upd_df.head(10)

,movie_id,title,year,mpaa,director,main_actor_1,main_actor_2,main_actor_3,main_actor_4,budget,domestic,genre_1,runtime_conv,full_date
0,tt0099165,The Bonfire of the Vanities,1990,R,Brian De Palma,Tom Hanks,Bruce Willis,Melanie Griffith,Kim Cattrall,47000000.0,15691192.0,Comedy,125,1990-12-22
1,tt0099611,Frankenhooker,1990,R,Frank Henenlotter,James Lorinz,Joanne Ritchie,Patty Mullen,J.J. Clark,2500000.0,205068.0,Comedy,85,1990-06-01
2,tt0099674,The Godfather: Part III,1990,R,Francis Ford Coppola,Al Pacino,Diane Keaton,Andy Garcia,Talia Shire,54000000.0,66666062.0,Crime,162,1990-12-25
3,tt0099747,Havana,1990,R,Sydney Pollack,Robert Redford,Lena Olin,Alan Arkin,Tomas Milian,40000000.0,9243140.0,Drama,144,1990-12-14
4,tt0100029,Lionheart,1990,R,Sheldon Lettich,Jean-Claude Van Damme,Harrison Page,Deborah Rennard,Lisa Pelikan,6000000.0,24078196.0,Action,108,1990-01-11
5,tt0100332,Paris Is Burning,1990,R,Jennie Livingston,Brooke Xtravaganza,André Christian,Dorian Corey,Paris Duprée,500000.0,3905297.0,Documentary,71,1990-08-09
6,tt0100405,Pretty Woman,1990,R,Garry Marshall,Richard Gere,Julia Roberts,Jason Alexander,Laura San Giacomo,14000000.0,178406268.0,Comedy,119,1990-03-23
7,tt0101356,Another You,1991,R,Maurice Phillips,Richard Pryor,Gene Wilder,Mercedes Ruehl,Stephen Lang,17000000.0,2865916.0,Comedy,98,1991-07-26
8,tt0101453,Billy Bathgate,1991,R,Robert Benton,Dustin Hoffman,Nicole Kidman,Loren Dean,Bruce Willis,48000000.0,15565363.0,Crime,106,1991-11-01
9,tt0101507,Boyz n the Hood,1991,R,John Singleton,Cuba Gooding Jr.,Laurence Fishburne,Hudhail Al-Amir,Lloyd Avery II,6500000.0,57504069.0,Crime,112,1991-07-12

In [15]:
mojo_upd_df.to_csv("MojoCleaned.csv")